### ISSUE TITLE
Remove old modules and related code/documentation

### ISSUE THREAD

**Issue by tyll** [nmstate/ansible-nmstate#13]
These modules will not be developed anymore and should be removed including all their documentation and other code that is specific for them:

nmstate_interface.py
nmstate_l3_interface.py
nmstate_linkagg.py

Also, the new module nmstate_apply.py should be documented.

**Comment by liangwen12year** [comment]
updated in this PR https://github.com/nmstate/ansible-nmstate/pull/14/commits

**Comment by tyll** [comment]
please move the example to the playbook directory

**Comment by liangwen12year** [comment]
> please move the example to the playbook directory

ok, I will update soon
