### ISSUE TITLE
Use "port" in "./playbooks/bond.yml" to replace "slaves"

### ISSUE THREAD

**Issue by liangwen12year** [nmstate/ansible-nmstate#23]
In order to use `port` instead of `slaves`, the nmstate version should be 0.4

**Comment by tyll** [comment]
What is the exact problem here? Why can version 0.4 not be used?

**Comment by ffmancera** [comment]
> What is the exact problem here? Why can version 0.4 not be used?

There is no issue here. Nmstate 0.4 can be used. I think @liangwen12year misunderstood the issue. The playbook needs to be updated. I will rename it.

**Comment by liangwen12year** [comment]
@tyll , I just found a hard time to install nmstate 0.4 in Centos8. I will follow it up with Fernando.

**Comment by liangwen12year** [comment]
updated in this PR, https://github.com/nmstate/ansible-nmstate/pull/24
